// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1gbEFgD0Dcl7Yeg5SgBGqPod0CQT4Nj4',
    appId: '1:430209792422:web:84687549b4b0f90db37767',
    messagingSenderId: '430209792422',
    projectId: 'durack-5af67',
    authDomain: 'durack-5af67.firebaseapp.com',
    databaseURL: 'https://durack-5af67.firebaseio.com',
    storageBucket: 'durack-5af67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPTWYovHVJ4VjbmX6kk3ZnlluPK8fye0',
    appId: '1:430209792422:android:fa11e3ca8168736fb37767',
    messagingSenderId: '430209792422',
    projectId: 'durack-5af67',
    databaseURL: 'https://durack-5af67.firebaseio.com',
    storageBucket: 'durack-5af67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFT1kV9oQyMOx-ynXpM6UkH43qfNYFT4',
    appId: '1:430209792422:ios:ec5db0f8c1880d9ab37767',
    messagingSenderId: '430209792422',
    projectId: 'durack-5af67',
    databaseURL: 'https://durack-5af67.firebaseio.com',
    storageBucket: 'durack-5af67.appspot.com',
    iosClientId: '430209792422-4pi2qloritm0lb88gvb8o7e0lkr6fqer.apps.googleusercontent.com',
    iosBundleId: 'io.x1opya.mafiahelper',
  );
}
